[package]
name = "warp_github_webhook"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
description = "GitHub webhook for Warp web framework"
license = "MIT/Apache-2.0"
repository = "https://gitlab.com/KonradBorowski/warp_github_webhook"
edition = "2018"

[dependencies]
hex = "0.3.2"
hmac = "0.7.0"
serde = "1.0.85"
serde_json = "1.0.36"
sha-1 = "0.8.1"
warp = "0.1.11"

[dev-dependencies]
serde_derive = "1.0.85"
