[package]
name = "warp_github_webhook"
version = "0.2.2"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
description = "GitHub webhook for Warp web framework"
license = "MIT/Apache-2.0"
repository = "https://gitlab.com/KonradBorowski/warp_github_webhook"
edition = "2018"

[dependencies]
github_webhook_message_validator = "0.1.2"
hex = "0.3.2"
serde = "1.0.85"
serde_json = "1.0.36"
warp = "0.1.11"

[dev-dependencies]
serde_derive = "1.0.85"
